Fix crashes on YAML serialization after dependency update
Tests started to crash with:

    yaml.representer.RepresenterError: cannot represent an object

... on fields using frozendict or frozenlist.
I'm not exactly sure what changed to introduce this error, as PyYAML has
not been updated recently.

It can be resolved by explicitly telling the YAML dumper how to
serialize those types.